version: "3.9"

services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 3000:80
    volumes:
      - ./pages:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./pages:/var/www/html

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
